# Ex2 - Getting and knowing your Data

### Step 1. Go to [Dataset_link](https://raw.githubusercontent.com/APSSDC-Data-Analysis/Data-Analysis-B3-Afternoon/master/D6_Preprocessing(29Aug2020)/titanic.csv)

* This dataset for Titanic passenger details
* Having columns are survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
* Some passengers were not found in their details (missing values are present)

## Step 2. Use the Csv file and assign it to a dataframe called titan_data

In [1]:
import pandas as pd
titan=pd.read_csv("titanic.csv")
titan_data=pd.DataFrame(titan)
titan_data.head()

survived  pclass                                               name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      sex   age  sibsp  parch            ticket     fare cabin embarked  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3  female  35.0      1      0            113803  53.1000  C123        S  
4    male  35.0      0      0            373450   8.0500   NaN        S

## Step 3. What is  the number of observations and entries in the dataset? 

In [2]:
print(titan_data.columns)
print(titan_data.index)

Index(['survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked'],
      dtype='object')
RangeIndex(start=0, stop=891, step=1)


## Step 4. Check the missing values and non-missing values  for every individual label

In [23]:
for i in list(titan_data.columns):
    print(i,"missing values are",titan_data[i].isnull().sum())
    print(i,"non_missing values are",titan_data[i].notnull().sum())

survived missing values are 0
survived non_missing values are 891
pclass missing values are 0
pclass non_missing values are 891
name missing values are 0
name non_missing values are 891
sex missing values are 0
sex non_missing values are 891
age missing values are 177
age non_missing values are 714
sibsp missing values are 0
sibsp non_missing values are 891
parch missing values are 0
parch non_missing values are 891
ticket missing values are 0
ticket non_missing values are 891
fare missing values are 0
fare non_missing values are 891
cabin missing values are 687
cabin non_missing values are 204
embarked missing values are 2
embarked non_missing values are 889


## Step 5. Replace missing values with mean value,If label having  numerics data and assign it to a new dataframe named as  titan_df

In [121]:
import numpy as np
col=[]
for i in list(titan_data.columns):
    if np.dtype(titan_data[i])==np.dtype("int64") or np.dtype(titan_data[i])==np.dtype("float64"):
        col.append(i)
titan_df=pd.DataFrame(titan_data[col].fillna(titan_data[col].mean()))
titan_df

survived  pclass        age  sibsp  parch     fare
0           0       3  22.000000      1      0   7.2500
1           1       1  38.000000      1      0  71.2833
2           1       3  26.000000      0      0   7.9250
3           1       1  35.000000      1      0  53.1000
4           0       3  35.000000      0      0   8.0500
..        ...     ...        ...    ...    ...      ...
886         0       2  27.000000      0      0  13.0000
887         1       1  19.000000      0      0  30.0000
888         0       3  29.699118      1      2  23.4500
889         1       1  26.000000      0      0  30.0000
890         0       3  32.000000      0      0   7.7500

[891 rows x 6 columns]

## Step 6. In titan_df, Replace missing values with mode value, if label having categorical data (object type) 

In [136]:
col=[]
for i in list(titan_data.columns):
    if np.dtype(titan_data[i])!=np.dtype("int64") and np.dtype(titan_data[i])!=np.dtype("float64"):
        col.append(i)
df=titan_data[col].mode().head()
df

name   sex    ticket        cabin embarked
0                    Abbing, Mr. Anthony  male      1601      B96 B98        S
1            Abbott, Mr. Rossmore Edward   NaN    347082  C23 C25 C27      NaN
2       Abbott, Mrs. Stanton (Rosa Hunt)   NaN  CA. 2343           G6      NaN
3                    Abelson, Mr. Samuel   NaN       NaN          NaN      NaN
4  Abelson, Mrs. Samuel (Hannah Wizosky)   NaN       NaN          NaN      NaN

In [137]:
titan_df=titan_data[col].replace(to_replace=np.nan,value=df.iloc[0])
titan_df

name     sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

               ticket    cabin embarked  
0           A/5 21171  B96 B98        S  
1            PC 17599      C85        C  
2    STON/O2. 3101282  B96 B98        S  
3              113803     C123        S  
4              373450  B96 B98        S  
..                ...      ...      ...  
886            211536  B96 B98        S  
887            112053      B42        S  
888        W./C. 6607  B96 B98        S  
889            111369     C148        C  
890            370376  B96 B98        Q  

[891 rows x 5 columns]

## Step 7. Now, check the missing values in titan_df

In [138]:
titan_df.isnull().sum()

name        0
sex         0
ticket      0
cabin       0
embarked    0
dtype: int64

## Step 8. Finally, Export titan_df to "cleaned_titan_df.xlsx"

In [140]:
titan_df.to_excel(r'cleaned_titan_df.xlsx', index = True)

# Task:
* Take same Dataset 
* Follow same steps by using Data imputation technique.
* Export final dataset to "cleaned_titan_df.csv"

In [152]:
titan_data=pd.read_csv("titanic.csv")
titan_data.head()

survived  pclass                                               name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      sex   age  sibsp  parch            ticket     fare cabin embarked  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3  female  35.0      1      0            113803  53.1000  C123        S  
4    male  35.0      0      0            373450   8.0500   NaN        S

In [144]:
from sklearn.impute import SimpleImputer

In [145]:
si=SimpleImputer(strategy="mean")

In [154]:
col=[]
for i in list(titan_data.columns):
    if np.dtype(titan_data[i])==np.dtype("int64") or np.dtype(titan_data[i])==np.dtype("float64"):
        col.append(i)
titan_df=si.fit_transform(titan_data[col])
titan_df

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  3.    , 24.    ,  1.    ,  2.    , 23.45  ],
       [ 1.    ,  1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 0.    ,  3.    , 32.    ,  0.    ,  0.    ,  7.75  ]])

In [161]:
si=SimpleImputer(strategy="constant",fill_value=-1)
titan_df=si.fit_transform(titan_data[col])
titan_df

array([[ 0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  3.    , -1.    ,  1.    ,  2.    , 23.45  ],
       [ 1.    ,  1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 0.    ,  3.    , 32.    ,  0.    ,  0.    ,  7.75  ]])

In [163]:
si=SimpleImputer(strategy="most_frequent")
titan_df=si.fit_transform(titan_data)
titan_df

array([[0, 3, 'Braund, Mr. Owen Harris', ..., 7.25, 'B96 B98', 'S'],
       [1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', ...,
        71.2833, 'C85', 'C'],
       [1, 3, 'Heikkinen, Miss. Laina', ..., 7.925, 'B96 B98', 'S'],
       ...,
       [0, 3, 'Johnston, Miss. Catherine Helen "Carrie"', ..., 23.45,
        'B96 B98', 'S'],
       [1, 1, 'Behr, Mr. Karl Howell', ..., 30.0, 'C148', 'C'],
       [0, 3, 'Dooley, Mr. Patrick', ..., 7.75, 'B96 B98', 'Q']],
      dtype=object)

In [164]:
titan_df=pd.DataFrame(titan_df,columns=titan_data.columns)
titan_df

survived pclass                                               name  \
0          0      3                            Braund, Mr. Owen Harris   
1          1      1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2          1      3                             Heikkinen, Miss. Laina   
3          1      1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4          0      3                           Allen, Mr. William Henry   
..       ...    ...                                                ...   
886        0      2                              Montvila, Rev. Juozas   
887        1      1                       Graham, Miss. Margaret Edith   
888        0      3           Johnston, Miss. Catherine Helen "Carrie"   
889        1      1                              Behr, Mr. Karl Howell   
890        0      3                                Dooley, Mr. Patrick   

        sex age sibsp parch            ticket     fare    cabin embarked  
0      male  22     1     0         A/5 21171     7.25  B96 B98        S  
1    female  38     1     0          PC 17599  71.2833      C85        C  
2    female  26     0     0  STON/O2. 3101282    7.925  B96 B98        S  
3    female  35     1     0            113803     53.1     C123        S  
4      male  35     0     0            373450     8.05  B96 B98        S  
..      ...  ..   ...   ...               ...      ...      ...      ...  
886    male  27     0     0            211536       13  B96 B98        S  
887  female  19     0     0            112053       30      B42        S  
888  female  24     1     2        W./C. 6607    23.45  B96 B98        S  
889    male  26     0     0            111369       30     C148        C  
890    male  32     0     0            370376     7.75  B96 B98        Q  

[891 rows x 11 columns]

In [165]:
titan_df.to_excel(r'cleaned_titan_df1.xlsx', index = True)